### ISSUE TITLE
"failed to make request to device" for a smart contract tx

### ISSUE THREAD

**Issue by mikheevm** [GridPlus/gridplus-sdk#172]
I get `failed to make request to device` error in the console when trying to create a wallet on https://gnosis-safe.io/app/#/welcome

**Steps to reproduce:**
1. Connect lattice wallet
2. Click "create new safe"
3. Follow the flow
4. Approve transaction on the device

**Expected outcome:**
The transaction goes through, a wallet is created

**Obtained outcome:**
Transaction fails 

Software versions:
GCE: 0.48.12
bootloader: 0.3.1
HSM: 0.11.0

**Comment by alex-miller-0** [comment]
@mikheevm Can you try to replicate this on Rinkeby? I am able to create a 2/2 safe.

**Comment by mikheevm** [comment]
With metamask thing you mentioned in another issue or with onboard.js?

**Comment by mikheevm** [comment]
I was on latest macOS/chrome btw

**Comment by alex-miller-0** [comment]
> With metamask thing you mentioned in another issue or with onboard.js?

With MetaMask. We've more or less deprecated the onboard.js integrations so I wouldn't trust any of them.

Another person replicated this so it looks specific to the EIP712 signature. I'm looking into it.

**Comment by mikheevm** [comment]
@alex-miller-0 I don't see grid+ option in my metamask. What do I miss?

**Comment by mikheevm** [comment]
https://web.gridplus.io/setup

Do you mean the metamask fork?

**Comment by alex-miller-0** [comment]
@mikheevm Yes sorry, the fork!

**Comment by alex-miller-0** [comment]
Closing this issue. This was fixed in d4555226f924311dfa02881be63e02d9d0fe47c3

See this for more discussion: https://github.com/gnosis/safe-react/issues/2652
