### ISSUE TITLE
cannot use wallet on rinkeby dApp

### ISSUE THREAD

**Issue by mikheevm** [GridPlus/gridplus-sdk#173]
Cannot use lattice wallet on rinkeby dapp: https://rinkeby.gnosis-safe.io/app/#/welcome

It opens a dev Heroku lattice wallet which timeouts when trying to connect to the wallet, the same dapp deployed on mainnet works fine

**Comment by alex-miller-0** [comment]
To find your production Lattice device you need to add your accounts while MetaMak is on mainnet. At that point you can switch to Rinkeby on MetaMask and use the Rinkeby-connected app.
