### ISSUE TITLE
Swap out `ethers-eip712`

### ISSUE THREAD

**Issue by alex-miller-0** [GridPlus/gridplus-sdk#215]
In #213 I got rid of the full, bloaty `ethers` module in favor of smaller packages that we actually use. Unfortunately, I have found that `ethers-eip712`, which we need for TypeData messages, requires the full `ethers` module as a dependency, so this SDK will break if that is not included.

I have looked at several EIP712 libs but none of them work for the test payloads so I can't use any of them right now. It isn't worth the trouble of fixing those other modules, so I will include `ethers` back in for now and come back to this.

The best option I found is a module called [`eip-712`](https://www.npmjs.com/package/eip-712). It failed on several payloads, but it looked like only two types of failures:

* `'Should test a large 1inch transaction'` threw some error internal to `eip-712`: `AssertionError: expected 'Failed to make request to device: data.startsWith is not a function' to equal null`
* `'Should test canonical EIP712 example with 3rd level nesting'` simply calculates the wrong hash. I opened [an issue](https://github.com/Mrtenz/eip-712/issues/34#issuecomment-1006863366) pointing this out. I looked at the code and it is not obvious what the issue is except to say that it is failing to build the final nested object into the definition. The `encodeType` function in `ethers-eip712` ([here](https://github.com/0xsequence/ethers-eip712/blob/master/src/typed-data.ts#L122)) is much more complex than the one in `eip-712` ([here](https://github.com/Mrtenz/eip-712/blob/master/src/eip-712.ts#L50)) so I think that code would probably just need to get replicated. Unfortunately that isn't the only problem so I can't just fork it and merge that in.

We should aim to get rid of `ethers-eip712` once we find a slimmer module that works with all the payloads we need.

I have started a branch to show what this swap could look like: https://github.com/GridPlus/gridplus-sdk/tree/fix-ethers-again

**Comment by FrederikBolding** [comment]
Seems that swapping this out is a good idea 👍 

I looked into your report with @Mrtenz today and it seems to us like `ethers-eip712` might have an issue. See this issue comment for more details: https://github.com/Mrtenz/eip-712/issues/35#issuecomment-1007405890

**Comment by alex-miller-0** [comment]
👀 

Very interesting. Thanks for pointing it out.
