### ISSUE TITLE
Figure out how Terra transactions should be built and add tests

### ISSUE THREAD

**Issue by alex-miller-0** [GridPlus/gridplus-sdk#260]
We want to add a Terra adapter and much of that work was started in this firmware branch: https://github.com/GridPlus/k8x_firmware_production/tree/terra-decode

And we have started mocking out tests in https://github.com/GridPlus/gridplus-sdk/tree/terra-support

The problem is we don't have any domain knowledge about how transactions should be built/serialized and the docs are very confusing. There are quite a lot of different things that can be encoded into a tx and it seems some of them are very uncommon, but idk how to evaluate what to encode.

In the [mock test](https://github.com/GridPlus/gridplus-sdk/blob/b02ec775e0f61a10cd7c7059607e683706a78cbe/test/testGeneric.ts#L412) (at the time of writing), we build a transaction object and serialize it. We then create a `SignDoc` and sign that. The result of these two encodings is different:

`tx.toBytes()`:

```
0a5d0a5b0a212f636f736d6f732e62616e6b2e763162657461312e4d73674d756c746953656e6412360a10120e0a05756c756e61120531303030300a10120e0a05756c756e61120531303030301210120e0a05756c756e6112053230303030120b12091080c0cef1ab81e411
```

Payload to `RawKey.ecdsaSign` (result of `SignDoc`):

```
0a5d0a5b0a212f636f736d6f732e62616e6b2e763162657461312e4d73674d756c746953656e6412360a10120e0a05756c756e61120531303030300a10120e0a05756c756e61120531303030301210120e0a05756c756e6112053230303030125b0a4e0a460a1f2f636f736d6f732e63727970746f2e736563703235366b312e5075624b657912230a2102d4f30206131dd69fcc23abfc272edf0eebcc0aac7465378c5d994dafd4ac780c12040a02080112091080c0cef1ab81e4111a09626f6d6261792d3132206f
```

So it looks like the tx bytes are a subset of the bytes to sign.

We need to figure out what we need to sign so that we can decode it. Fortunately, Terra Station (the main wallet) is open source: https://github.com/terra-money/station

Let's clone Terra Station, get it hooked up to a testnet, and find out how they are building txs.

**Update:** It looks like there is also [Terra Station extension](https://github.com/terra-money/station-extension) which is probably where we need to look

**Comment by douglance** [comment]
Terra is ded
