### ISSUE TITLE
Order 4byte results oldest to newest

### ISSUE THREAD

**Issue by alex-miller-0** [GridPlus/gridplus-sdk#410]
We use a util `fetchCalldataDecoder` to check for the definition of a function defined in EVM calldata. We use 4byte as a fallback ([here](https://github.com/GridPlus/gridplus-sdk/blob/v1.3.5/src/util.ts#L476)).

Apparently some people have started griefing this registry by inserting new colliding definitions. This will still be a tricky attack vector because a collision using the same param types would likely require a change to the function name (and given the collision space it would probably need to be an unreadable name), but nevertheless we should make the simple change to **select the oldest 4byte result**, as has been done here: https://github.com/GridPlus/gridplus-sdk/blob/v1.3.5/src/util.ts#L476

**Comment by douglance** [comment]
Did you mean to link to [this MetaMask commit](https://github.com/MetaMask/metamask-extension/pull/14937/files#diff-c8c256cb0389d020fcf5c440c7133f063c3d2a1b6321b3252d23cd0208bb79dbR38) for the implementation reference?

**Comment by alex-miller-0** [comment]
Yes lol thank you
