### ISSUE TITLE
[Integration] Upgrade MetaMask browser extension to v2.1.0

### ISSUE THREAD

**Issue by KevinVitale** [GridPlus/gridplus-sdk#417]
- [x] [Release SDK v2.1.0](https://github.com/GridPlus/gridplus-sdk/pull/418)
 - [x] [Update eth-lattice-keyring](https://github.com/GridPlus/eth-lattice-keyring/issues/42)
 - [x] [Open a PR upstream](https://github.com/MetaMask/metamask-extension/pulls)

**Comment by douglance** [comment]
Live for all supported browsers.
