### ISSUE TITLE
sdk incorrectly encodes EIP712 payloads?

### ISSUE THREAD

**Issue by shrugs** [GridPlus/gridplus-sdk#452]
i'm narrowing down an issue where attempting to sign an EIP712 payload with a lattice produces an invalid signature, and one of my hunches is that the encoding of the payload is incorrect, since recovery of a signature against a payload with a field of type `uint256` fails if that field's value is 22 decimal characters or longer.

context:
https://github.com/floating/frame/issues/988

**Comment by alex-miller-0** [comment]
Noting this example. I will look into this.

https://github.com/floating/frame/issues/988#issuecomment-1219027001

**Comment by alex-miller-0** [comment]
@shrugs sorry about this and thank you so much for your background work. We identified the issue as an unknown deficiency in displaying large integer strings in `bignumber.js`. We will get this patched and updated soon. Frame is good about including our updates quickly. MetaMask will take a bit longer but it looks like you're a Frame user anyway :)
